### ISSUE TITLE
Compatibility error with Chinese version Blender

### ISSUE THREAD

**Issue by qazesc** [wikid24/ffxiv_mmd_tools_helper#2]
Thank u so much for creating this amazing plugin.
For a long time now, when I click the Leg/Foot IK button, I always get many errors that prevent me from using the plugin properly.
I am a user of the Chinese version of Blender, and after switching back to the English version, this problem that had been bothering me for over a month disappeared.
I think this may be a problem with the underlying code of Blender, not only your plugin, but other plugins like: ARP also have the same problem.
I don't know if this problem, which only exists in the Chinese version, can be fixed, but if it is convenient, please mark this problem on the page. Finally, please allow me to give my best regards to you who developed this plugin!

**Comment by wikid24** [comment]
![image](https://user-images.githubusercontent.com/19479648/226087066-26aef676-c605-40fe-acf7-48382790bd1b.png)


error provided by user

**Comment by wikid24** [comment]
![image](https://user-images.githubusercontent.com/19479648/227037727-0289c5b2-7389-4d66-b3f2-526af01bfe3a.png)

error provided by another user
