### ISSUE TITLE
Can't enable blender add-on without mek_tools

### ISSUE THREAD

**Issue by SodiumShine** [wikid24/ffxiv_mmd_tools_helper#4]
Blender 3.6.5
Add-on version 0.859
mmd_tools add-on is also installed and enabled

The FFXIV MMD Tools Helper add-on is downloaded and installed fine but it cannot be enabled without manually installing mek_tools which is specified in the guide as optional. 

> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
>     mod = __import__(module_name)
>   File "C:\Users\Na\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\__init__.py", line 102, in <module>
>     from . import shaders
>   File "C:\Users\Na\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\ffxiv_mmd_tools_helper\shaders.py", line 500, in <module>
>     import mek_tools
> ModuleNotFoundError: No module named 'mek_tools'

**Comment by wikid24** [comment]
fixed
